---
version: 2
plan:
  project-key: IN
  key: INSECURE-BANK
  name: Build the bank

stages:
  - Build hull:
    - Build

Build:
  tasks:
    - script:
      - ./mvnw clean package -DskipTests
      - docker build -t insecure-bank-web:${bamboo.buildKey} .
