---
version: 2
plan:
  project-key: IN
  key: INSECUREBANK
  name: Build the bank

stages:
  - Build bank:
    - Build

Build:
  tasks:
    - script:
      - ./mvnw clean package -DskipTests
      - echo 'BAMSCRT@0@0@tD/Vy/s8NErYyFQGynAhOA=='
      - ./xlw apply -v --values=BUILD_NUMBER=${bamboo.buildNumber} --xl-release-url http://xl-release:5516 --xl-release-password BAMSCRT@0@0@tD/Vy/s8NErYyFQGynAhOA== --xl-deploy-url http://xl-deploy:4516 --xl-deploy-password BAMSCRT@0@0@tD/Vy/s8NErYyFQGynAhOA== -f start-release.yaml
